if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager",repos = "http://cran.us.r-project.org")
BiocManager::install("ChIPseeker")
BiocManager::install("GenomicFeatures")
BiocManager::install("ChIPpeakAnno")
BiocManager::install("clusterProfiler")
